### ISSUE TITLE
Page class not delivered to frontend

### ISSUE THREAD

**Issue by operatorone** [asconsulting/zyppy_class#4]
Hi, when I set a Page Classes in the settings they are not delivered to the source code in the body tag. 
Can you check this please?

Cheers,
Tilman

**Comment by asconsulting** [comment]
I have confirmed this as working in my demo site. You may have another module overriding the page class. Without more specifics, I can't diagnose further.

**Comment by operatorone** [comment]
Yeah, you're right. I applied a class to an empty page and it's there. It couldn't be applied if there is already a CSS class in the page settings defined. Maybe it could be added additionally but not necessary.
